stages:
- build
- upload
- release

variables:
  BINARY: "commit-test-${CI_COMMIT_TAG}.vsix"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/binaries/${CI_COMMIT_TAG}"

build:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --global vsce
  script:
    - npm install
    - vsce package
  artifacts:
    paths:
      - "*.vsix"

upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${BINARY}" "${PACKAGE_REGISTRY_URL}/${BINARY}"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "${CI_COMMIT_TAG}" --description "TBD" --tag-name "${CI_COMMIT_TAG}" \
        --assets-link "{\"name\":\"${BINARY}\"},\"url\":\"${PACKAGE_REGISTRY_URL}/${BINARY}\""
