stages:
- build
- release

build_job:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --global vsce
  script:
    - npm install
    - vsce package
  artifacts:
    paths:
      - "*.vsix"

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TAG'
    description: 'TBD'
    tag_name: '$CI_COMMIT_TAG'
