stages:
- release

release:
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --global vsce
  script:
    - npm install
    - vsce package
  artifacts:
    paths:
      - "*.vsix"
