stages:
- release

release_job:
  stage: release
  image: node:latest
  rules:
    - if: $CI_COMMIT_TAG
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --global vsce
  script:
    - npm install
    - vsce package
  artifacts:
    paths:
      - "*.vsix"
  release:
    name: '$CI_COMMIT_TAG'
    description: 'commit-test $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'

